#!/usr/bin/env bash

mono=${MONO:=0}
dotnet=${DOTNET:=0}

case "$1" in
  dotnet)
    dotnet=1
    mono=0
    ;;
  mono)
    mono=1
    dotnet=0
    ;;
esac

if [ $dotnet -eq 1 ]; then
	dotnet run -c Release -f netcoreapp2.0 -p ${TRAVIS_BUILD_DIR}/src/Multiformats.Hash.CLI/Multiformats.Hash.CLI.csproj -- "$@"
fi

if [ $mono -eq 1 ]; then
	mono ${TRAVIS_BUILD_DIR}/src/Multiformats.Hash.CLI/bin/x64/Release/net461/Multiformats.Hash.CLI.exe "$@"
fi
